server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus" # Actuator API
  endpoint:
    health:
      show-details: always # health Status

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "monitoring-group"
  data:
    redis:
      host: localhost
      port: 6379